/** @type {import('next').NextConfig} */
const nextConfig = {
  // Output standalone build for Docker deployment (commented out for local dev)
  // output: "standalone",
  
  // Enable strict mode for better error detection
  reactStrictMode: true,
  
  // API rewrites to FastAPI backend
  async rewrites() {
    return [
      // Mail tracking proxy — forwards branded skyrate.ai/api/mail/* links
      // to the mail.skyrate.ai worker (DO App 7743f6e0-9a31-433d-8ef0-3bf3367bfaa3).
      // These must come BEFORE the /api/:path* catch-all.
      // Short-form paths generated by tracking.py (base_url/t/c/:token and base_url/t/o/:token)
      {
        source: "/api/mail/t/o/:token",
        destination: "https://skyratemail-65jh2.ondigitalocean.app/t/o/:token",
      },
      {
        source: "/api/mail/t/c/:token",
        destination: "https://skyratemail-65jh2.ondigitalocean.app/t/c/:token",
      },
      {
        source: "/api/mail/track/open/:token",
        destination: "https://skyratemail-65jh2.ondigitalocean.app/t/o/:token",
      },
      {
        source: "/api/mail/track/click/:token",
        destination: "https://skyratemail-65jh2.ondigitalocean.app/t/c/:token",
      },
      {
        source: "/api/mail/unsub",
        destination: "https://skyratemail-65jh2.ondigitalocean.app/unsub",
      },
      {
        source: "/api/:path*",
        destination: `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8001"}/api/:path*`,
      },
    ];
  },
  
  // Headers for CORS and PWA
  async headers() {
    return [
      {
        source: "/api/:path*",
        headers: [
          { key: "Access-Control-Allow-Credentials", value: "true" },
          { key: "Access-Control-Allow-Origin", value: "*" },
          { key: "Access-Control-Allow-Methods", value: "GET,POST,PUT,DELETE,OPTIONS" },
          { key: "Access-Control-Allow-Headers", value: "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version" },
        ],
      },
      {
        // Service worker must be served from root with no-cache
        source: "/sw.js",
        headers: [
          { key: "Cache-Control", value: "no-cache, no-store, must-revalidate" },
          { key: "Content-Type", value: "application/javascript; charset=utf-8" },
          { key: "Service-Worker-Allowed", value: "/" },
        ],
      },
      {
        source: "/manifest.json",
        headers: [
          { key: "Cache-Control", value: "public, max-age=3600" },
          { key: "Content-Type", value: "application/manifest+json" },
        ],
      },
    ];
  },
};

module.exports = nextConfig;
