name: skyrate-ai
region: nyc

# Global environment variables
envs:
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "false"

services:
  # ===========================================
  # FastAPI Backend
  # ===========================================
  - name: backend
    github:
      repo: yourusername/erateapp.com  # UPDATE THIS
      branch: main
      deploy_on_push: true
    source_dir: /opendata/skyrate-ai-v2/backend
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/mo - upgrade for production
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DEEPSEEK_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
    cors:
      allow_origins:
        - prefix: https://
        - exact: ${frontend.PUBLIC_URL}
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allow_headers:
        - Content-Type
        - Authorization
      allow_credentials: true

  # ===========================================
  # Next.js Frontend
  # ===========================================
  - name: frontend
    github:
      repo: yourusername/erateapp.com  # UPDATE THIS
      branch: main
      deploy_on_push: true
    source_dir: /opendata/skyrate-ai-v2/frontend
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/mo - upgrade for production
    health_check:
      http_path: /
      initial_delay_seconds: 20
      period_seconds: 30
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_AND_BUILD_TIME
        value: ${backend.PUBLIC_URL}
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: NEXTAUTH_URL
        scope: RUN_TIME
        value: ${APP_URL}

# ===========================================
# Managed PostgreSQL Database
# ===========================================
databases:
  - name: db
    engine: PG
    version: "15"
    production: false  # Set to true for production (higher tier)
    cluster_name: skyrate-db
    db_name: skyrate
    db_user: skyrate_user

# ===========================================
# Optional: Jobs for scheduled tasks
# ===========================================
# jobs:
#   - name: sync-usac-data
#     github:
#       repo: yourusername/erateapp.com
#       branch: main
#     source_dir: /opendata/skyrate-ai-v2/backend
#     run_command: python -m app.jobs.sync_usac
#     kind: PRE_DEPLOY
#     instance_size_slug: basic-xxs
#     envs:
#       - key: DATABASE_URL
#         scope: RUN_TIME
#         value: ${db.DATABASE_URL}

# ===========================================
# Alerts (optional)
# ===========================================
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: DEPLOYMENT_LIVE
