name: skyrate
region: fra

domains:
  - domain: skyrate.ai
    type: PRIMARY
  - domain: www.skyrate.ai
    type: ALIAS

services:
  # Backend API (FastAPI/Python)
  - name: backend
    github:
      repo: orelmeister/skyrate
      branch: main
      deploy_on_push: true
    source_dir: backend
    environment_slug: python
    instance_count: 1
    instance_size_slug: apps-s-2vcpu-4gb
    http_port: 8000
    build_command: pip install -r requirements.txt
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envs:
      - key: SECRET_KEY
        scope: RUN_TIME
        value: WvFKVgkDWd4KVcfz1mUOkuSx_oXXZO57cgYl71P7A0c
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: DEBUG
        scope: RUN_TIME
        value: "false"
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: VAPID_PRIVATE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: VAPID_PUBLIC_KEY
        scope: RUN_TIME
        value: BOQ_1ePgEdPmLcqMCOwM1XGJakthkvFnt3AuCJaGZMs-gm71tz7QorrUdZzBwK-6XWX_SwaRlnO02jyZZNzM-8I
      - key: VAPID_CONTACT_EMAIL
        scope: RUN_TIME
        value: alerts@skyrate.ai
      - key: SMTP_HOST
        scope: RUN_TIME
        value: smtp.gmail.com
      - key: SMTP_PORT
        scope: RUN_TIME
        value: "587"
      - key: SMTP_USER
        scope: RUN_TIME
        value: david@skyrate.ai
      - key: SMTP_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: FROM_EMAIL
        scope: RUN_TIME
        value: alerts@skyrate.ai
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: https://skyrate.ai
    routes:
      - path: /api

  # Frontend (Next.js)
  - name: frontend
    github:
      repo: orelmeister/skyrate
      branch: main
      deploy_on_push: true
    source_dir: frontend
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-2vcpu-4gb
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: BUILD_TIME
        value: https://skyrate.ai/api
      - key: NEXT_PUBLIC_VAPID_KEY
        scope: BUILD_TIME
        value: BOQ_1ePgEdPmLcqMCOwM1XGJakthkvFnt3AuCJaGZMs-gm71tz7QorrUdZzBwK-6XWX_SwaRlnO02jyZZNzM-8I
    routes:
      - path: /
